# Generated by Django 5.1.4 on 2024-12-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_rename_question_type_question_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="long_ans",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="forms.user",
            ),
        ),
    ]
