# Generated by Django 5.1.4 on 2024-12-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_alter_answer_long_ans_alter_answer_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={("question", "user")},
        ),
    ]
